{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "frontend.fullname" . }}-spc
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  provider: azure
  secretObjects:
    {{- range .Values.secretProviderClass.secrets }}
    - secretName: {{ .name }}
      type: Opaque
      data:
        - objectName: {{ .objectName }}
          key: {{ .key }}
    {{- end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: ""
    keyvaultName: {{ .Values.secretProviderClass.keyVaultName | quote }}
    tenantId: {{ .Values.secretProviderClass.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.secretProviderClass.secrets }}
        - |
          objectName: {{ .objectName }}
          objectType: secret
        {{- end }}
{{- end }}
